server:
  port: 8090

spring:
  application:
    name: cicd-jenkins-todeploy
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/users #cloud-native-cicd-jenkins-tobuild
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true #SQL 실행문 로그로 기록
    properties:
      hibernate:
        format_sql: true #pretty format
        highlight_sql : true #colored
  data:
#    mongodb:
#      database: cyberops
#    redis:
#      host: localhost
#      port: 6379

logging:
  level:
    org.springframework.batch.item.database: DEBUG

greeting:
  message: Welcome to Jenkins project.